/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.variantroute;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int colorAccent=0x7f030002;
        public static final int colorPrimary=0x7f030000;
        public static final int colorPrimaryDark=0x7f030001;
    }
    public static final class id {
        public static final int button=0x7f050002;
        public static final int container=0x7f050000;
        public static final int textView=0x7f050001;
    }
    public static final class layout {
        public static final int activity_main=0x7f020000;
        public static final int fragment_simple=0x7f020001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        /**  TODO: Remove or change this placeholder text 
         */
        public static final int hello_blank_fragment=0x7f040001;
    }
}
